version: "3.9"
services:

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=orders
    networks:
      - net-backend
    ports:
      - 3306:3306
    expose:
      - "3306"
  aasb-orders:
    build:
      dockerfile: Dockerfile
    container_name: aasb-orders-api
    restart: on-failure
    environment:
       SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://localhost:3306/aasb-plataforma?createDatabaseIfNotExist=true&useSSL=false&useTimezone=true&serverTimezone=America/Sao_Paulo",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root"       
        }'
    ports:
      - 8091:8091
    expose:
      - 8091
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - net-backend
networks:
  net-backend:
    driver: bridge

